# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#
# Triangle	 	T_n=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	 	P_n=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	H_n=n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T_285 = P_165 = H_143 = 40755.
#
# Find the next triangle number that is also pentagonal and hexagonal.


from functions.Integer import Triangular
from functions.Integer import Pentagonal
from functions.Integer import Hexagonal

from functions.Integer import isSquare
from functions.Integer import isTriangular
from functions.Integer import isPentagonal
from functions.Integer import isHexagonal


def run():
	Maxim = 10
	# for i in range(1, Maxim +1):
	# 	print(isHexagonal(Hexagonal(i)))
	# pass
	k = 143
	while True:
		k = k +1
		Num = Hexagonal(k)
		if not isPentagonal(Num):
			continue
		elif not isTriangular(Num):
			continue
		else:
			print(Num, k)
			break
# 1533776805
