# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even -valued terms.


def evenFibSum(maximum):
	from functions.Integer import IsEven
	fib_1 = 1
	fib_2 = 1
	temp_fib_1 = 1
	temp_fib_2 = 1

	fibSum = 0

	while(fib_2)<maximum:
		temp_fib_1 = fib_2
		temp_fib_2 = fib_1 + fib_2

		fib_1 = temp_fib_1
		fib_2 = temp_fib_2

		if IsEven(fib_2):
			fibSum = fibSum +fib_2
	return fibSum


if __name__=="__main__":
	print(evenFibSum(4000000))
